services:
  - type: web
    name: global-gravity-cms-v2
    env: node
    plan: free
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      # 🔑 安全密钥（保持唯一即可）
      - key: APP_KEYS
        value: "1234567890abcdef,abcdef1234567890"
      - key: API_TOKEN_SALT
        value: "abcdef9876543210abcdef9876543210"
      - key: ADMIN_JWT_SECRET
        value: "11223344556677889900aabbccddeeff"
      - key: TRANSFER_TOKEN_SALT
        value: "ffeeddccbbaa00998877665544332211"
      - key: JWT_SECRET
        value: "a1b2c3d4e5f6g7h8i9j0klmnopqrstuv"
      # 🔗 数据库（SQLite 本地文件）
      - key: DATABASE_CLIENT
        value: sqlite
      - key: DATABASE_FILENAME
        value: /data/data.db

disk:
  name: data
  mountPath: /data
  sizeGB: 1